"""
Offline test harness for the YouTube cookie pool (portal/youtube_cookie_pool.py)
and the YouTube half of app.py's fetch cookie-selection logic.

Deterministic: no network, no yt-dlp, no Flask, no project database. The pool
module imports only stdlib so it loads directly; app.py's selection logic is
AST-extracted as source text and its decisions replayed here.

The point this suite exists to defend:

    Instagram CANNOT be fetched without a live session cookie, so an exhausted
    pool there is a genuine dead end. YouTube fetches fine WITHOUT any cookie
    most of the time -- the alternate player_client is the primary mechanism and
    cookies are the bot-gate fallback. So configuring YOUTUBE_COOKIES must never
    REMOVE the cookieless path that works today.

Run:  python scripts/simulate_youtube_cookie_rotation.py   (exit 0 = all pass)
"""
import io
import os
import re
import sys
import tempfile
import time

sys.path.insert(0, os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'portal'))
import youtube_cookie_pool as ycp  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
APP = io.open(os.path.join(ROOT, 'portal', 'app.py'), encoding='utf-8').read()
GITIGNORE = io.open(os.path.join(ROOT, '.gitignore'), encoding='utf-8-sig').read()

PASS = 0


def ok(label, extra=''):
    global PASS
    PASS += 1
    print('  ok  %-60s %s' % (label, extra))


def _cookie_text(uid, domain='.youtube.com'):
    """A well-formed Netscape cookie file as a browser would export it."""
    return (
        "# Netscape HTTP Cookie File\n"
        "# This file is generated by a browser\n"
        f"{domain}\tTRUE\t/\tTRUE\t9999999999\tSID\tsid-{uid}\n"
        f"{domain}\tTRUE\t/\tTRUE\t9999999999\tHSID\thsid-{uid}\n"
    )


# ---------------------------------------------------- 1. bootstrap ---------
print('\n[1. the pool is built from the environment, and only from it]')

TMP = tempfile.mkdtemp(prefix='brandr_yt_cookie_sim_')
for _k in [k for k in os.environ if k.startswith('YOUTUBE_COOKIES')]:
    del os.environ[_k]

ycp.bootstrap_pool(TMP)
assert ycp.pool_size() == 0
ok('no env vars -> empty pool', 'app.py then takes the cookieless path')

os.environ['YOUTUBE_COOKIES'] = _cookie_text('base')
ycp.bootstrap_pool(TMP)
assert ycp.pool_size() == 1, ycp.pool_size()
ok('YOUTUBE_COOKIES alone gives a pool of 1')

# The whole numbered range must be honoured, not just a couple of slots.
for i in range(1, 11):
    os.environ[f'YOUTUBE_COOKIES_{i}'] = _cookie_text(i)
ycp.bootstrap_pool(TMP)
assert ycp.pool_size() == 11, ycp.pool_size()
ok('YOUTUBE_COOKIES_1 .. _10 are all read', 'base + 10 = 11')

os.environ['YOUTUBE_COOKIES_11'] = _cookie_text(11)
ycp.bootstrap_pool(TMP)
assert ycp.pool_size() == 11, 'slot _11 was read; the documented cap is _10'
del os.environ['YOUTUBE_COOKIES_11']
ok('_11 is ignored', 'the cap is the documented one')

# Google exports frequently carry .google.com rather than .youtube.com.
os.environ['YOUTUBE_COOKIES_1'] = _cookie_text('g', domain='.google.com')
ycp.bootstrap_pool(TMP)
assert ycp.pool_size() == 11
ok('a .google.com export is accepted', 'real exports are mixed-domain')

# Garbage must not silently become a "cookie" that burns a rotation slot.
for junk in ('', '   ', 'not a cookie file at all',
             '# only comments\n# nothing else\n',
             '.instagram.com\tTRUE\t/\tTRUE\t9999999999\tsessionid\tx'):
    os.environ['YOUTUBE_COOKIES_2'] = junk
    ycp.bootstrap_pool(TMP)
    assert ycp.pool_size() == 10, (junk[:20], ycp.pool_size())
ok('empty, malformed and wrong-site values are rejected', '5 shapes')

# Found by running a real fetch through Flask: a header-less value passed
# validation, entered the pool, and then failed EVERY fetch with
# "does not look like a Netscape format cookies file" -- which is not an auth
# failure, so it did not rotate. One malformed env var killed the whole fetch
# and surfaced an absolute server path to the user.
os.environ['YOUTUBE_COOKIES_2'] = (
    '.youtube.com\tTRUE\t/\tTRUE\t9999999999\tSID\tsid-noheader\n')
ycp.bootstrap_pool(TMP)
_written = [p for p in ycp.candidates_lru() if p.endswith('cookies_2.txt')]
assert _written, 'a header-less but otherwise valid export was rejected outright'
_body = io.open(_written[0], encoding='utf-8').read()
assert _body.startswith('# Netscape HTTP Cookie File\n'), _body[:60]
ok('a header-less export gets the Netscape header on write', 'yt-dlp requires it')
assert 'sid-noheader' in _body
ok('and the cookie lines themselves are untouched')

os.environ['YOUTUBE_COOKIES_2'] = _cookie_text(2)
ycp.bootstrap_pool(TMP)
_same = [p for p in ycp.candidates_lru() if p.endswith('cookies_2.txt')][0]
assert io.open(_same, encoding='utf-8').read() == _cookie_text(2), \
    'a value that already had the header was modified'
ok('a value that already has the header is written byte-identical')

assert ycp.is_auth_failure(
    "ERROR: '/srv/portal/data/youtube_pool/cookies_1.txt' does not look like a "
    "Netscape format cookies file")
ok('an unusable cookie file rotates instead of killing the fetch',
   'no server path reaches the user')
os.environ['YOUTUBE_COOKIES_2'] = _cookie_text(2)
ycp.bootstrap_pool(TMP)
assert ycp.pool_size() == 11


# ------------------------------------------------- 2. no leakage -----------
print('\n[2. cookie VALUES never leave the process]')

SECRET = 'sid-base'
for path in ycp.candidates_lru():
    assert SECRET not in os.path.basename(path)
ok('the filename carries no cookie value')

snap = ycp.health_snapshot()
assert snap and all(SECRET not in str(entry) for entry in snap)
assert all(set(e) == {'name', 'fails', 'cooling_down',
                      'cooldown_remaining_s', 'last_used_ago_s'} for e in snap)
ok('health_snapshot reports names and counters only')

src = io.open(os.path.join(ROOT, 'portal', 'youtube_cookie_pool.py'),
              encoding='utf-8').read()
for bad in ('print(raw', 'print(f"{raw', '{raw}', 'return raw'):
    assert bad not in src, 'the pool module can emit a raw cookie value: %s' % bad
ok('the module never prints or returns a raw value')

# Written cookie files are credentials. The env var is the source of truth.
for pat in ('portal/data/pool/', 'portal/data/youtube_pool/'):
    assert pat in GITIGNORE, '%s is NOT gitignored - cookies could be committed' % pat
ok('both pool directories are gitignored', 'env-only, never in Git')


# --------------------------------------------- 3. LRU and cooldown ---------
print('\n[3. rotation is least-recently-used, and failures cool down]')

for k in [k for k in os.environ if k.startswith('YOUTUBE_COOKIES')]:
    del os.environ[k]
os.environ['YOUTUBE_COOKIES'] = _cookie_text('A')
os.environ['YOUTUBE_COOKIES_1'] = _cookie_text('B')
os.environ['YOUTUBE_COOKIES_2'] = _cookie_text('C')
ycp.bootstrap_pool(TMP)
assert ycp.pool_size() == 3

first = ycp.candidates_lru()[0]
ycp.mark_used(first)
time.sleep(0.01)
assert ycp.candidates_lru()[-1] == first, 'a just-used cookie is not last'
ok('the most recently used cookie sorts last')

ycp.mark_bad(first)
assert first not in ycp.candidates_lru(), 'a failed cookie is still offered'
assert ycp.pool_size() == 3, 'mark_bad removed it from the pool instead of cooling it'
ok('a failed cookie is withheld but not discarded', 'cooldown, not deletion')

ycp.mark_success(first)
assert first in ycp.candidates_lru()
ok('success clears the cooldown and the fail count')

# Every cookie cooling down at once must be survivable, not fatal.
for p in list(ycp.candidates_lru()):
    ycp.mark_bad(p)
assert ycp.candidates_lru() == [], ycp.candidates_lru()
assert ycp.pool_size() == 3
ok('all cookies cooling down yields NO candidates', 'the dangerous state')


# ------------------------------------ 4. auth-failure discrimination -------
print('\n[4. only failures another cookie could fix count as auth failures]')

for text in ('ERROR: Sign in to confirm you’re not a bot',
             'Use --cookies-from-browser or --cookies for the authentication',
             'ERROR: unable to download video data: HTTP Error 403: Forbidden',
             'This video may be inappropriate for some users',
             'Sign in to confirm your age'):
    assert ycp.is_auth_failure(text), text
ok('bot-gate, cookie-hint, 403 and age-gate all rotate', '5 phrases')

for text in ('ERROR: Video unavailable',
             'ERROR: Private video. Sign in if you’ve been granted access to this video',
             'ERROR: This video has been removed by the uploader',
             'ERROR: unable to resolve host name',
             'ERROR: Unsupported URL: https://example.com/x',
             'ERROR: The uploader has not made this video available in your country',
             ''):
    assert not ycp.is_auth_failure(text), text
ok('unavailable, removed, network, unsupported and geo do NOT rotate',
   'ordinary failures cannot burn the pool')

# The signature is "sign in to confirm", not bare "sign in", so yt-dlp's private
# video wording ("Sign in if you've been granted access") does NOT rotate. That
# is correct and load-bearing -- a private video is a content fact, and another
# cookie for the same account cannot change it. Pinned so nobody loosens the
# signature to "sign in" and quietly turns every private link into a full pool
# sweep.
assert not ycp.is_auth_failure(
    "ERROR: Private video. Sign in if you've been granted access to this video")
ok('a private video does NOT rotate', 'the signature is not bare "sign in"')


# ------------------------- 5. app.py's YouTube selection contract ----------
print('\n[5. app.py keeps YouTube\'s cookieless path alive]')

SEL = APP[APP.index('active_cookie_pool = None'):]
SEL = SEL[:SEL.index('info = None')]

assert 'elif is_youtube and youtube_cookie_pool.pool_size() > 0' in SEL
ok('YouTube selects its own pool, never Instagram\'s')
assert re.search(r'if is_youtube:\s*\n(\s*#.*\n)+\s*cookie_candidates = cookie_candidates \+ \[None\]', SEL), \
    'YouTube has no cookieless final candidate -- configuring cookies would ' \
    'REMOVE the path that works today'
ok('a cookieless attempt is appended for YouTube', 'THE regression this guards')
assert 'cookie_candidates + [None]' not in SEL[:SEL.index('if is_youtube:')], \
    'Instagram also got a cookieless candidate'
ok('Instagram gets no cookieless candidate', 'IG genuinely needs a cookie')

# Breaker is Instagram-only state; calling it on the YouTube pool would raise.
for call in ('breaker_open', 'trip_breaker', 'reset_breaker', 'breaker_remaining'):
    assert not hasattr(ycp, call), 'the YouTube pool grew Instagram breaker state'
FETCH = APP[APP.index('def fetch_videos_from_urls'):]
FETCH = FETCH[:FETCH.index('\n@app.route', 10)]
for m in re.finditer(r'cookie_pool\.(breaker_open|trip_breaker|reset_breaker|breaker_remaining)\(', FETCH):
    window = FETCH[max(0, m.start() - 260):m.start()]
    assert 'is_meta' in window, 'an unguarded breaker call would AttributeError on YouTube'
ok('every breaker call is guarded by is_meta', 'no AttributeError on YouTube')

# The cookieless candidate must stay LAST. app.py's rotation branch calls
# os.path.basename(_cookie) when a cookie auth-fails and another candidate
# remains; reaching that with the None candidate would raise TypeError. It is
# unreachable only because None is last, so pin the ordering rather than the
# accident.
assert re.search(
    r'cookie_candidates = cookie_candidates \+ \[None\]\s*\n\s*else:', SEL), \
    'something touches cookie_candidates after the cookieless entry is appended'
ok('nothing reorders the list after None is appended', 'None stays last')
_rot = FETCH[FETCH.index('rotating to next cookie') - 400:FETCH.index('rotating to next cookie')]
assert '_idx < len(cookie_candidates) - 1' in _rot, \
    'the rotation branch no longer excludes the last candidate -- basename(None) would raise'
ok('the rotation branch never runs on the last candidate', 'no basename(None)')

# The proxy story must stay exactly as it was: the explicit IG_PROXY line only.
_yt = FETCH[FETCH.index('if is_youtube:'):]
_yt = _yt[:_yt.index('# Apply TikTok')]
assert "os.environ.get('IG_PROXY', '')" in _yt and "ydl_opts['proxy'] = _ig_proxy" in _yt
ok('YouTube still honours an explicit IG_PROXY', 'pre-existing, unchanged')
assert 'get_meta_proxy' not in _yt, 'the Meta-scoped proxy service was broadened to YouTube'
ok('proxy_service.get_meta_proxy() was NOT broadened', 'still Meta-only')

# One fetch must stay one fetch: rotation is retries, not extra jobs.
assert FETCH.count('increment_downloads(') == 1
_inc = FETCH.index('increment_downloads(')
assert _inc > FETCH.index('if info is None:'), 'accounting sits inside the cookie loop'
assert 'success_count' in FETCH[_inc:_inc + 60]
ok('rotation does not inflate the daily fetch count', 'counted once, per URL')


# --------------------------------- 6. replay the real loop's decisions -----
print('\n[6. replaying the loop: what actually happens to a YouTube fetch]')


def replay(candidates, auth_fail, content_fail=()):
    """Mirror app.py's loop. Returns (winner, cooled_down, hard_failure)."""
    tried_bad, cooled = [], []
    for idx, cookie in enumerate(candidates):
        name = os.path.basename(cookie) if cookie else None
        if cookie:
            ycp.mark_used(cookie)
        if name in content_fail:
            return 'CONTENT_ERROR', cooled, False
        if name in auth_fail:
            if idx < len(candidates) - 1:
                tried_bad.append(cookie)
                continue
            return None, cooled, True
        if cookie:
            ycp.mark_success(cookie)
        cooled = list(tried_bad)          # app.py cools them on ANY success
        return (name or 'COOKIELESS'), cooled, False
    return None, cooled, True


for k in [k for k in os.environ if k.startswith('YOUTUBE_COOKIES')]:
    del os.environ[k]
os.environ['YOUTUBE_COOKIES'] = _cookie_text('A')
os.environ['YOUTUBE_COOKIES_1'] = _cookie_text('B')
ycp.bootstrap_pool(TMP)
pool = ycp.candidates_lru()
names = [os.path.basename(p) for p in pool]

win, cooled, hard = replay(pool + [None], auth_fail=set())
assert win == names[0] and not hard
ok('healthy pool: the first cookie wins', win)

win, cooled, hard = replay(pool + [None], auth_fail={names[0]})
assert win == names[1] and cooled == [pool[0]] and not hard
ok('one dead cookie: rotates, and cools only the dead one')

win, cooled, hard = replay(pool + [None], auth_fail=set(names))
assert win == 'COOKIELESS' and not hard, (win, hard)
assert cooled == pool, 'cookies that failed where NO cookie worked were not cooled'
ok('every cookie dead: falls back to a cookieless fetch', 'NOT a hard failure')

win, cooled, hard = replay([None], auth_fail=set())
assert win == 'COOKIELESS' and not hard
ok('pool entirely cooled down (no candidates): still fetches')

win, cooled, hard = replay(pool + [None], auth_fail={names[0]},
                           content_fail={names[1]})
assert win == 'CONTENT_ERROR' and cooled == []
ok('a private/removed video stops at once', 'no cookie is cooled, none burned')

win, cooled, hard = replay([None], auth_fail={None})
assert hard and win is None
ok('cookieless ALSO failing is the only hard failure', 'and it says so')

import shutil
shutil.rmtree(TMP, ignore_errors=True)
for k in [k for k in os.environ if k.startswith('YOUTUBE_COOKIES')]:
    del os.environ[k]

print('\n%d assertions passed.' % PASS)
